name: Deploy to Wiki
on:
  push:
    branches:
      - develop
    paths:
      - 'wiki/**'
  # Triggers this workflow when the wiki is changed
  # (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#gollum).
  gollum:

jobs:
  table_of_contents_check:
    name: Wiki Check Table of Contents match Headers
    runs-on: ubuntu-20.04
    env:
      CACHE_DIRECTORY: ~/.bazel_cache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.0.0

      - name: Wiki Check Table of Contents
        id: wikichecktoc
        run: |
          bazel run //scripts:wiki_table_of_contents_check -- ${GITHUB_WORKSPACE}

  wiki-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        run: |
          git filter-branch --subdirectory-filter wiki/ -- --all
          git remote set-url origin https://github.com/oppia/oppia-android.wiki.git
          git checkout -b master
          git push origin master --force
